- client/components/Problem.js
- client/components/Prompt.js
- client/components/QuestionScreen.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- package-lock.json
- public/index.html
- public/style.css
- Added QuestionScreen, Prompt and Problem components
- Added picture of The Commish
> Sara proof

- client/components/Correct.js
- client/components/Problem.js
- client/components/QuestionScreen.js
- client/components/Wrong.js
- client/components/index.js
- client/routes.js
text box shows what regex is returning and submit button sends them to a correct of wrong component
> added try and submit

- .travis.yml
> feat(root): hook up travis

- package-lock.json
- package.json
> FIX(modules): updated lodash

- script/gameData.js
- script/seed.js
- server/api/users.spec.js
- server/db/models/game.js
- server/db/models/index.js
- server/db/models/user.js
- server/db/models/user.spec.js
> User model

- server/db/models/user.js
> FIX(models/user): added casefile

- script/gameData.js
> ADD(gameData): addedclues

- client/routes.js
Added 'exact' to front end routes.
> FIX: front end routes

- client/components/Correct.js
- client/components/Incorrect.js
- client/components/Problem.js
- client/store/user.js
- script/gameData.js
- server/api/users.js
correct and incorrect components pull from database and move user to correct question
> Intersticials

- client/components/Problem.js
- client/components/QuestionScreen.js
- Added local state toggle to the QuestionScreen component to check if game data has been fetched before rendering, resets at componentDidUnmount.
> FIX: question screen game data fetch

- client/components/Casefile.js
- client/components/Crossroads.js
- public/style.css
clues display on crossroads component
> BUILD(Components/Crossroads): clues display

- client/components/Correct.js
- client/components/navbar.js
- public/style.css
> BUILD(components/correct): added casefile notification

- client/components/Boss.js
- script/bossData.js
hopefully i got the syntax errors this time
> Final boss

- package-lock.json
- package.json
> Added Material

- client/app.js
- client/components/Boss.js
- client/components/Chase.js
- client/components/PostBoss.js
- client/routes.js
> STYLE(components/Boss): added material UL

- client/components/Chase.js
- client/components/Crossroads.js
- public/style.css
> STYLE(components/crossroads): styled crossroads

- client/components/QuestionScreen.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> remove comments

- client/app.js
- client/components/Boss.js
- client/components/Scroll.js
- client/components/navbar.js
- client/routes.js
- public/style.css
- script/bossData.js
Logout is now at the bottom of the screen, on history push user is now automatically at the top of the page.
> FIX(Client/routes): scrolls to the top on change

- script/gameData.js
> (script/gameData): added linebreaks

- client/components/Boss.js
- client/components/ExplainEx.js
- client/components/PostBoss.js
- client/components/Problem.js
- script/bossData.js
-ghost gif
-countdown counts down instead of up
-everything submits on enter as well as button click
-question icon added to explainEx
-longer haystack in boss level
> STYLE(components/postboss): added ghost gif

- client/components/Boss.js
- client/components/Problem.js
- client/components/QuestionScreen.js
- script/bossData.js
> STYLE(components/Boss): styled

- client/components/Loading.js
- client/components/QuestionScreen.js
> START LOADING SCREEN

- client/components/CasefileIcon.js
- client/components/ConsoleIcon.js
- client/components/LessonIcon.js
- client/components/NotesIcon.js
- client/components/Problem.js
- client/components/QuestionScreen.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> Styling tweaks

- client/components/Loading.js
- client/components/NoMore.js
- client/components/PostBoss.js
- client/components/QuestionScreen.js
- public/style.css
- script/gameData.js
> BUILD(components/Questionscreen): added skip button

- client/components/PostBoss.js
> FIX(Components/Postboss): fixed win issue

- client/components/Crossroads.js
> FIX(components/Chase): updated loading

- script/bossData.js
- script/clusterData.js
- script/gameData.js
> FIX(overall): changed Grepino to GREP Crime Syndicate
